#!/usr/bin/env bash
# Sync LLM keys from dotnet user-secrets into .env for docker-compose.
# DB / RabbitMQ connection strings are NOT synced — docker-compose supplies those.
set -euo pipefail

SECRETS_FILE="$HOME/.microsoft/usersecrets/139d1811-05fe-45f2-98ea-f8b45dc746cd/secrets.json"

if [ ! -f "$SECRETS_FILE" ]; then
  echo "ERROR: User secrets not found at $SECRETS_FILE"
  exit 1
fi

python3 - "$SECRETS_FILE" << 'PYEOF'
import sys, json, os

with open(sys.argv[1], encoding="utf-8-sig") as f:
    s = json.load(f)

env_map = {
    "Llm:ApiKey":       "LLM_API_KEY",
    "Llm:BaseUrl":      "LLM_BASE_URL",
    "Llm:DefaultModel": "LLM_DEFAULT_MODEL",
    "Llm:Provider":     "LLM_PROVIDER",
}

lines = ["# Auto-generated by sync-secrets.sh — do not edit manually or commit.\n"]
for secret_key, env_key in env_map.items():
    val = s.get(secret_key)
    if val:
        lines.append(f"{env_key}={val}\n")

with open(".env", "w") as f:
    f.writelines(lines)

print("Written to .env:")
for l in lines[1:]:
    k, v = l.rstrip().split("=", 1)
    masked = v[:6] + "***" if len(v) > 6 else "***"
    print(f"  {k}={masked}")
PYEOF
