// <auto-generated />
using System;
using AiOrchestrator.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiOrchestrator.Infrastructure.Migrations
{
    [DbContext(typeof(AiOrchestratorDbContext))]
    [Migration("20260602070415_AddTemplates")]
    partial class AddTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiOrchestrator.Domain.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_json");

                    b.Property<string>("PromptText")
                        .HasColumnType("text")
                        .HasColumnName("prompt_text");

                    b.Property<string>("RawOutput")
                        .HasColumnType("text")
                        .HasColumnName("raw_output");

                    b.Property<bool>("SchemaValid")
                        .HasColumnType("boolean")
                        .HasColumnName("schema_valid");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("StepRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_run_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("TokenUsageJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("token_usage_json");

                    b.HasKey("Id");

                    b.HasIndex("StepRunId");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("idx_agent_run_task");

                    b.ToTable("agent_run", (string)null);
                });

            modelBuilder.Entity("AiOrchestrator.Domain.AgentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_code");

                    b.Property<string>("AllowedDataSourcesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_data_sources_json");

                    b.Property<string>("AllowedSkillsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_skills_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MaxToolCalls")
                        .HasColumnType("integer")
                        .HasColumnName("max_tool_calls");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("OutputSchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("output_schema_json");

                    b.Property<string>("ScenarioCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scenario_code");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("temperature");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioCode", "AgentCode")
                        .HasDatabaseName("idx_agent_template_scenario_code");

                    b.ToTable("agent_template", (string)null);
                });

            modelBuilder.Entity("AiOrchestrator.Domain.AiTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrentStep")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_step");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<string>("ScenarioCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scenario_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioCode")
                        .HasDatabaseName("idx_ai_task_scenario");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_ai_task_status");

                    b.ToTable("ai_task", (string)null);
                });

            modelBuilder.Entity("AiOrchestrator.Domain.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("artifact_type");

                    b.Property<string>("ContentJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<Guid?>("StepRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_run_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("StepRunId");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("idx_artifact_task");

                    b.ToTable("artifact", (string)null);
                });

            modelBuilder.Entity("AiOrchestrator.Domain.EvidenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtractedValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("extracted_value_json");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<int?>("PageNo")
                        .HasColumnType("integer")
                        .HasColumnName("page_no");

                    b.Property<string>("QuoteText")
                        .HasColumnType("text")
                        .HasColumnName("quote_text");

                    b.Property<string>("SectionTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("section_title");

                    b.Property<string>("SourceName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("idx_evidence_task");

                    b.ToTable("evidence_item", (string)null);
                });

            modelBuilder.Entity("AiOrchestrator.Domain.ReviewItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("text")
                        .HasColumnName("review_comment");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("Reviewer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reviewer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("StepRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_run_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("StepRunId");

                    b.HasIndex("TaskId", "Status")
                        .HasDatabaseName("idx_review_task_status");

                    b.ToTable("review_item", (string)null);
                });

            modelBuilder.Entity("AiOrchestrator.Domain.SkillRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_json");

                    b.Property<string>("SkillCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skill_code");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("StepRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_run_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("StepRunId");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("idx_skill_run_task");

                    b.ToTable("skill_run", (string)null);
                });

            modelBuilder.Entity("AiOrchestrator.Domain.TraceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid?>("StepRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_run_id");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid?>("WorkflowRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id");

                    b.HasIndex("StepRunId");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("idx_trace_task");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("trace_event", (string)null);
                });

            modelBuilder.Entity("AiOrchestrator.Domain.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stored_file_path");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("uploaded_file", (string)null);
                });

            modelBuilder.Entity("AiOrchestrator.Domain.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("context_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("WorkflowCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("workflow_code");

                    b.Property<string>("WorkflowVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workflow_version");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("idx_workflow_run_task");

                    b.ToTable("workflow_run", (string)null);
                });

            modelBuilder.Entity("AiOrchestrator.Domain.WorkflowStepRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_json");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("step_id");

                    b.Property<string>("StepName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("step_name");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("step_type");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("WorkflowRunId")
                        .HasDatabaseName("idx_step_run_workflow");

                    b.HasIndex("WorkflowRunId", "StepId")
                        .IsUnique()
                        .HasDatabaseName("idx_step_run_workflow_step");

                    b.ToTable("workflow_step_run", (string)null);
                });

            modelBuilder.Entity("AiOrchestrator.Domain.WorkflowStepTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_code");

                    b.Property<string>("DataSourceBindingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data_source_bindings_json");

                    b.Property<string>("DependsOnJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("depends_on_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("SkillCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skill_code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("step_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_template_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowTemplateId")
                        .HasDatabaseName("idx_step_template_workflow");

                    b.ToTable("workflow_step_template", (string)null);
                });

            modelBuilder.Entity("AiOrchestrator.Domain.WorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("InputSchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_schema_json");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("ScenarioCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scenario_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioCode", "IsActive")
                        .HasDatabaseName("idx_workflow_template_scenario_active");

                    b.ToTable("workflow_template", (string)null);
                });

            modelBuilder.Entity("AiOrchestrator.Domain.AgentRun", b =>
                {
                    b.HasOne("AiOrchestrator.Domain.WorkflowStepRun", "StepRun")
                        .WithMany()
                        .HasForeignKey("StepRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiOrchestrator.Domain.AiTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StepRun");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AiOrchestrator.Domain.Artifact", b =>
                {
                    b.HasOne("AiOrchestrator.Domain.WorkflowStepRun", "StepRun")
                        .WithMany()
                        .HasForeignKey("StepRunId");

                    b.HasOne("AiOrchestrator.Domain.AiTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StepRun");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AiOrchestrator.Domain.EvidenceItem", b =>
                {
                    b.HasOne("AiOrchestrator.Domain.AiTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AiOrchestrator.Domain.ReviewItem", b =>
                {
                    b.HasOne("AiOrchestrator.Domain.WorkflowStepRun", "StepRun")
                        .WithMany()
                        .HasForeignKey("StepRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiOrchestrator.Domain.AiTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StepRun");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AiOrchestrator.Domain.SkillRun", b =>
                {
                    b.HasOne("AiOrchestrator.Domain.WorkflowStepRun", "StepRun")
                        .WithMany()
                        .HasForeignKey("StepRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiOrchestrator.Domain.AiTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StepRun");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AiOrchestrator.Domain.TraceEvent", b =>
                {
                    b.HasOne("AiOrchestrator.Domain.WorkflowStepRun", "StepRun")
                        .WithMany()
                        .HasForeignKey("StepRunId");

                    b.HasOne("AiOrchestrator.Domain.AiTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.HasOne("AiOrchestrator.Domain.WorkflowRun", "WorkflowRun")
                        .WithMany()
                        .HasForeignKey("WorkflowRunId");

                    b.Navigation("StepRun");

                    b.Navigation("Task");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("AiOrchestrator.Domain.UploadedFile", b =>
                {
                    b.HasOne("AiOrchestrator.Domain.AiTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AiOrchestrator.Domain.WorkflowRun", b =>
                {
                    b.HasOne("AiOrchestrator.Domain.AiTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AiOrchestrator.Domain.WorkflowStepRun", b =>
                {
                    b.HasOne("AiOrchestrator.Domain.AiTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiOrchestrator.Domain.WorkflowRun", "WorkflowRun")
                        .WithMany()
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("AiOrchestrator.Domain.WorkflowStepTemplate", b =>
                {
                    b.HasOne("AiOrchestrator.Domain.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("AiOrchestrator.Domain.WorkflowTemplate", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
